[package]
name = "tulip"
version = "0.1.0"
authors = ["Nycta <rawieo@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = { git = "https://github.com/dom-lis/tui-rs", branch = "serde", features = ["serde"] }
termion = { git = "https://github.com/dom-lis/termion", branch = "serde", features = ["serde"] }
clap = "3.0.0-beta.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.61"
