[package]
name = "tulip"
version = "0.1.0"
authors = ["Nycta <rawieo@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1.5.6"
clap = "3.0.0-beta.2"
unicode-segmentation = "1.8.0"
regex = "1"
