[package]
name = "tulip"
version = "0.1.0"
authors = ["Nycta <rawieo@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1.5.6"
clap = { version = "3.0.10", features = ["derive"] }
tui = { version = "0.17.0", features = ["termion"] }
fltk = { version = "1.2.27", features = ["fltk-bundled"] }
simplelog = "0.11.2"
log = "0.4.14"
unicode-segmentation = "1.8.0"
serde = { version = "1.0.135", features = ["derive"] }
serde_json = "1.0.78"
